# --- MADDPG specific parameters ---

runner: "episode"

buffer_size: 10000
# update the target network every {} episodes
target_update_interval_or_tau: 1

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

# use the madddpg_learner to train
mac: "maddpg_mac"
agent: "n_rnn"
reg: 0.001
batch_size: 32
lr: 0.003
use_rnn: True
common_reward: True
standardise_returns: False
standardise_rewards: True
rnn_hidden_dim: 256
learner: "maddpg_learner"
agent_output_type: "pi_logits"
hidden_dim: 256
critic_type: "maddpg_critic"
name: "maddpg"
